version: "3"

services:
  web:
    build:
      context: ./docker/web
      args:
        - TZ=${TZ}
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      - ./logs/php:/var/log/php
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
